trigger:
  batch: true
  branches:
    include:
    - puff_master

pool: mypool

stages:
- stage: Build
  jobs:
  - job:
    container:
      image: sonicdev-microsoft.azurecr.io:443/sonic-slave-bullseye:latest
    steps:
    - checkout: self
      clean: true
    - script: |
        sudo apt-get update
        sudo apt-get install -y make libboost-all-dev libgtest-dev build-essential swig4.0
      displayName: "Install dependencies"  
    - task: DownloadPipelineArtifact@2
      inputs:
        source: specific
        project: build
        pipeline: puffc.sonic-buildimage
        artifact: sonic-buildimage.vs1
        buildVersionToDownload: latest
        allowFailedBuilds: true
        allowPartiallySucceededBuilds: true
        path: $(Build.ArtifactStagingDirectory)/download
        itemPattern: |
          target/debs/bullseye/libprotobuf*.deb
          target/debs/bullseye/libprotoc*.deb
          target/debs/bullseye/protobuf-compiler*.deb
      displayName: "Download libyang packages"
    - script: |
        set -ex
        sudo dpkg -i $(find ./download -name *.deb)
      workingDirectory: $(Build.ArtifactStagingDirectory)
      displayName: "Install libyang from common lib"
    - script: |
        mkdir -p package
        dpkg-buildpackage -rfakeroot -us -uc -b -j$(nproc)
        cp ../*.deb package/
      displayName: "Build sonic-dash-api"
    - publish: $(System.DefaultWorkingDirectory)/package
      artifact: sonic-dash-api-bullseye